import { StyleSheet } from 'react-native';
import { colors } from '../../style/colors';
import { fontScale, radiusScale, spaceScale } from '../../style/responsive';

export const quizBoardStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: colors.background,
  },
  loadingSafeArea: {
    flex: 1,
    backgroundColor: colors.background,
  },
  screenGradient: {
    flex: 1,
    backgroundColor: colors.background,
  },
  backgroundGlowTop: {
    position: 'absolute',
    top: -80,
    right: -70,
    width: 220,
    height: 220,
    borderRadius: 110,
    backgroundColor: 'rgba(20,184,166,0.18)',
  },
  backgroundGlowBottom: {
    position: 'absolute',
    left: -90,
    bottom: 140,
    width: 240,
    height: 240,
    borderRadius: 120,
    backgroundColor: 'rgba(56,189,248,0.12)',
  },
  thumbsBurstOverlay: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 5,
  },
  thumbsBurst: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.12)',
    paddingHorizontal: 18,
    paddingVertical: 12,
    borderRadius: 999,
  },
  thumbEmoji: {
    fontSize: 40,
    marginHorizontal: 4,
  },
  thumbLeft: {
    transform: [{ rotate: '-18deg' }],
  },
  thumbRight: {
    transform: [{ rotate: '16deg' }],
  },
  fixedTopSection: {
    paddingHorizontal: spaceScale(16),
    paddingTop: spaceScale(16),
  },
  scrollContent: {
    paddingHorizontal: spaceScale(16),
    paddingTop: spaceScale(16),
    paddingBottom: spaceScale(40),
  },
  topBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  compactControlsWrap: {
    position: 'relative',
    alignItems: 'flex-start',
    width: '100%',
  },
  compactLauncherRow: {
    flexDirection: 'row',
    alignItems: 'center',
    width: '100%',
    gap: 8,
  },
  compactScreenActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flex: 1,
    minWidth: 0,
    justifyContent: 'flex-start',
  },
  navHomeHit: {
    width: 42,
    flexShrink: 0,
  },
  navHomeButton: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#0B7285',
    shadowOpacity: 0.18,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 4,
  },
  compactNextHit: {
    flex: 1,
    minWidth: 0,
  },
  compactPrevHit: {
    flex: 1,
    minWidth: 0,
  },
  compactPrevButton: {
    minHeight: 42,
    borderRadius: 21,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 10,
    shadowColor: '#0B7285',
    shadowOpacity: 0.18,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 4,
  },
  compactPrevText: {
    color: '#F8FBFF',
    fontSize: fontScale(12),
    fontWeight: '900',
    letterSpacing: 0.2,
    textAlign: 'center',
  },
  compactNextButton: {
    minHeight: 42,
    borderRadius: 21,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 10,
    shadowColor: '#0F766E',
    shadowOpacity: 0.2,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 4,
  },
  compactNextText: {
    color: '#F8FBFF',
    fontSize: fontScale(12),
    fontWeight: '900',
    letterSpacing: 0.2,
    textAlign: 'center',
  },
  compactClockGlyph: {
    color: '#F4F7FF',
    fontSize: 20,
    fontWeight: '900',
    lineHeight: 20,
  },
  compactEnglishHit: {
    flex: 1,
    minWidth: 0,
  },
  compactEnglishButton: {
    minHeight: 42,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 10,
    shadowColor: '#0EA5E9',
    shadowOpacity: 0.18,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 4,
  },
  shortcutRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  shortcutIconWrap: {
    width: 24,
    height: 24,
    alignItems: 'center',
    justifyContent: 'center',
  },
  compactEnglishText: {
    color: '#F8FBFF',
    fontSize: fontScale(10),
    fontWeight: '900',
    letterSpacing: 0.2,
    textTransform: 'uppercase',
    textAlign: 'center',
  },
  languageActionRow: {
    marginTop: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    flexWrap: 'wrap',
    width: '100%',
  },
  englishPillHit: {
    flexShrink: 0,
  },
  tutorialPillHit: {
    flexShrink: 0,
  },
  englishPill: {
    minWidth: 112,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 999,
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#0F766E',
    shadowOpacity: 0.18,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
    elevation: 5,
  },
  englishPillGlow: {
    position: 'absolute',
    left: -8,
    top: -10,
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: 'rgba(255,255,255,0.20)',
    transform: [{ rotate: '22deg' }],
  },
  englishPillText: {
    color: '#F8FBFF',
    fontSize: fontScale(10),
    fontWeight: '900',
    letterSpacing: 0.5,
    textTransform: 'uppercase',
    textAlign: 'center',
  },
  tutorialPill: {
    minWidth: 126,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 999,
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#0EA5E9',
    shadowOpacity: 0.18,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 7 },
    elevation: 4,
  },
  tutorialPillGlow: {
    position: 'absolute',
    right: -10,
    top: -10,
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: 'rgba(255,255,255,0.16)',
    transform: [{ rotate: '-18deg' }],
  },
  tutorialPillText: {
    color: '#F8FBFF',
    fontSize: 11,
    fontWeight: '900',
    letterSpacing: 0.4,
    textTransform: 'uppercase',
  },
  remoteEmoji: {
    fontSize: 16,
    fontWeight: '900',
    color: '#F4F7FF',
  },
  emptyState: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 22,
    backgroundColor: colors.background,
  },
  emptyArtWrap: {
    width: '100%',
    maxWidth: 340,
    aspectRatio: 1.22,
    marginBottom: 18,
  },
  emptyArt: {
    width: '100%',
    height: '100%',
  },
  emptyCopyCard: {
    width: '100%',
    maxWidth: 340,
    paddingHorizontal: 20,
    paddingVertical: 18,
    borderRadius: 24,
    backgroundColor: 'rgba(255,255,255,0.08)',
    borderWidth: 1,
    borderColor: 'rgba(125,211,252,0.18)',
  },
  emptyHomeButtonHit: {
    width: '100%',
    maxWidth: 240,
    marginTop: 18,
    borderRadius: 999,
    overflow: 'hidden',
  },
  emptyHomeButton: {
    minHeight: 52,
    paddingHorizontal: 22,
    borderRadius: 999,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.16)',
  },
  emptyHomeIcon: {
    color: '#F8F4FF',
    fontSize: 18,
    fontWeight: '900',
    lineHeight: 18,
  },
  emptyHomeText: {
    color: '#F8F4FF',
    fontSize: 15,
    fontWeight: '900',
    letterSpacing: 0.4,
  },
  emptyTitle: {
    fontSize: 25,
    fontWeight: '800',
    color: colors.textDark,
    textAlign: 'center',
  },
  emptyText: {
    marginTop: 10,
    textAlign: 'center',
    color: colors.textMuted,
    fontSize: 15,
    lineHeight: 22,
  },
  quizCard: {
    marginTop: 14,
    backgroundColor: 'rgba(250,253,255,0.98)',
    borderRadius: radiusScale(32),
    padding: spaceScale(12),
    borderWidth: 1,
    borderColor: 'rgba(125,211,252,0.18)',
    shadowColor: '#04131D',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.14,
    shadowRadius: 18,
    elevation: 8,
  },
  questionPanel: {
    minHeight: 100,
    borderRadius: radiusScale(26),
    paddingHorizontal: spaceScale(18),
    paddingTop: spaceScale(18),
    paddingBottom: spaceScale(20),
    justifyContent: 'center',
    backgroundColor: '#F2FFF4',
    borderWidth: 1,
    borderColor: 'rgba(22,163,74,0.12)',
  },
  questionMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  questionMetaRowReversed: {
    flexDirection: 'row-reverse',
  },
  panelTitle: {
    color: '#5C7D66',
    fontSize: fontScale(10),
    fontWeight: '700',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
    flex: 1,
    marginRight: 10,
  },
  panelTitleRight: {
    marginRight: 0,
    marginLeft: 10,
    textAlign: 'right',
  },
  questionCounterText: {
    fontSize: fontScale(13),
    fontWeight: '800',
    color: '#1B3B2C',
    textAlign: 'right',
  },
  questionTitle: {
    color: '#183728',
    textAlign: 'left',
    fontSize: fontScale(18),
    lineHeight: fontScale(25),
    fontWeight: '800',
  },
  questionActionRow: {
    marginTop: spaceScale(14),
    alignItems: 'flex-end',
    marginBottom: spaceScale(2),
  },
  questionLanguageSection: {
    marginTop: spaceScale(12),
  },
  questionLanguageHeaderRow: {
    marginBottom: spaceScale(8),
    paddingHorizontal: spaceScale(2),
  },
  questionLanguageHeading: {
    color: '#5D7771',
    fontSize: fontScale(11),
    fontWeight: '800',
    letterSpacing: 0.3,
  },
  timeRow: {
    marginTop: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  timeClockWrap: {
    width: 44,
    height: 44,
    marginRight: 8,
    flexShrink: 0,
    alignItems: 'center',
    justifyContent: 'center',
  },
  timeBar: {
    flex: 1,
    height: 8,
    borderRadius: 999,
    backgroundColor: '#DDEAF0',
    overflow: 'hidden',
  },
  timeFill: {
    height: '100%',
    borderRadius: 999,
  },
  timeValue: {
    marginLeft: 8,
    color: '#163042',
    fontSize: fontScale(12),
    fontWeight: '700',
    minWidth: 52,
    textAlign: 'right',
    lineHeight: 16,
    includeFontPadding: false,
    textAlignVertical: 'center',
  },
  optionsGroup: {
    marginTop: 16,
  },
  feedbackSection: {
    marginTop: 16,
  },
  feedbackCard: {
    marginBottom: 14,
    backgroundColor: '#EEFAF1',
    borderRadius: 20,
    padding: 14,
    borderWidth: 1,
    borderColor: 'rgba(20,184,166,0.14)',
  },
  feedbackRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  crossCircle: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: '#F97316',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 8,
  },
  crossText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '700',
  },
  feedback: {
    flex: 1,
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '600',
  },
  correct: {
    color: colors.success,
  },
  incorrect: {
    color: '#F97316',
  },
  answerText: {
    marginTop: 8,
    color: '#6F8794',
    fontSize: 13,
    lineHeight: 18,
  },
  feedbackPlaceholder: {
    marginBottom: 14,
    backgroundColor: '#EEFAF1',
    borderRadius: 18,
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderWidth: 1,
    borderColor: 'rgba(20,184,166,0.16)',
  },
  feedbackPlaceholderText: {
    color: '#6F8794',
    fontSize: fontScale(12),
    lineHeight: fontScale(17),
    textAlign: 'center',
  },
});
