import { StyleSheet } from 'react-native';
import { colors } from '../../style/colors';

export const quizBoardStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: colors.background,
  },
  loadingSafeArea: {
    flex: 1,
    backgroundColor: colors.background,
  },
  screenGradient: {
    flex: 1,
    backgroundColor: colors.background,
  },
  backgroundGlowTop: {
    position: 'absolute',
    top: -80,
    right: -70,
    width: 220,
    height: 220,
    borderRadius: 110,
    backgroundColor: 'rgba(139,92,246,0.12)',
  },
  backgroundGlowBottom: {
    position: 'absolute',
    left: -90,
    bottom: 140,
    width: 240,
    height: 240,
    borderRadius: 120,
    backgroundColor: 'rgba(96,165,250,0.08)',
  },
  fixedTopSection: {
    paddingHorizontal: 16,
    paddingTop: 12,
  },
  scrollContent: {
    paddingHorizontal: 16,
    paddingTop: 10,
    paddingBottom: 28,
  },
  topBar: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    flexWrap: 'wrap',
    gap: 8,
  },
  compactControlsWrap: {
    position: 'relative',
    alignItems: 'flex-start',
    width: '100%',
  },
  compactControlsButtonHit: {
    width: 46,
    height: 46,
    borderRadius: 23,
    overflow: 'hidden',
  },
  compactControlsButton: {
    width: 46,
    height: 46,
    borderRadius: 23,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#8B5CF6',
    shadowOpacity: 0.25,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 5,
  },
  compactControlsButtonText: {
    color: '#F8F4FF',
    fontSize: 20,
    fontWeight: '900',
    lineHeight: 20,
  },
  compactControlsPanel: {
    marginTop: 10,
    width: '100%',
  },
  compactLauncherRow: {
    flexDirection: 'row',
    alignItems: 'center',
    width: '100%',
    gap: 8,
  },
  compactScreenActions: {
    flex: 1,
    minWidth: 0,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    gap: 10,
  },
  compactNextHit: {
    flex: 1,
    minWidth: 0,
  },
  compactNextButton: {
    height: 42,
    borderRadius: 21,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#8B5CF6',
    shadowOpacity: 0.22,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 4,
  },
  compactNextText: {
    color: '#F8F4FF',
    fontSize: 13,
    fontWeight: '900',
    letterSpacing: 0.2,
  },
  compactEnglishHit: {
    flex: 1,
    minWidth: 0,
  },
  compactEnglishButton: {
    height: 42,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#E953B8',
    shadowOpacity: 0.22,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 4,
  },
  compactEnglishText: {
    color: '#F8F4FF',
    fontSize: 11,
    fontWeight: '900',
    letterSpacing: 0.2,
    textTransform: 'uppercase',
  },
  languageSection: {
    alignItems: 'center',
    flexShrink: 1,
  },
  languageActionRow: {
    marginTop: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    flexWrap: 'wrap',
    width: '100%',
  },
  englishPillHit: {
    flexShrink: 0,
  },
  tutorialPillHit: {
    flexShrink: 0,
  },
  englishPill: {
    minWidth: 120,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 999,
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#E953B8',
    shadowOpacity: 0.26,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
    elevation: 5,
  },
  englishPillGlow: {
    position: 'absolute',
    left: -8,
    top: -10,
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: 'rgba(255,255,255,0.20)',
    transform: [{ rotate: '22deg' }],
  },
  englishPillText: {
    color: '#F8F4FF',
    fontSize: 11,
    fontWeight: '900',
    letterSpacing: 0.5,
    textTransform: 'uppercase',
  },
  tutorialPill: {
    minWidth: 126,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 999,
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#4D8CFF',
    shadowOpacity: 0.22,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 7 },
    elevation: 4,
  },
  tutorialPillGlow: {
    position: 'absolute',
    right: -10,
    top: -10,
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: 'rgba(255,255,255,0.16)',
    transform: [{ rotate: '-18deg' }],
  },
  tutorialPillText: {
    color: '#F8F4FF',
    fontSize: 11,
    fontWeight: '900',
    letterSpacing: 0.4,
    textTransform: 'uppercase',
  },
  remoteEmoji: {
    fontSize: 16,
    fontWeight: '900',
    color: '#F4F7FF',
  },
  emptyState: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 22,
    backgroundColor: colors.background,
  },
  emptyArtWrap: {
    width: '100%',
    maxWidth: 340,
    aspectRatio: 1.22,
    marginBottom: 18,
  },
  emptyArt: {
    width: '100%',
    height: '100%',
  },
  emptyCopyCard: {
    width: '100%',
    maxWidth: 340,
    paddingHorizontal: 20,
    paddingVertical: 18,
    borderRadius: 24,
    backgroundColor: 'rgba(255,255,255,0.06)',
    borderWidth: 1,
    borderColor: 'rgba(124,233,248,0.18)',
    shadowColor: '#0A102E',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.22,
    shadowRadius: 20,
    elevation: 6,
  },
  emptyHomeButtonHit: {
    width: '100%',
    maxWidth: 240,
    marginTop: 18,
    borderRadius: 999,
    overflow: 'hidden',
  },
  emptyHomeButton: {
    minHeight: 52,
    paddingHorizontal: 22,
    borderRadius: 999,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.16)',
    shadowColor: '#1B2F79',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.24,
    shadowRadius: 18,
    elevation: 6,
  },
  emptyHomeIcon: {
    color: '#F8F4FF',
    fontSize: 18,
    fontWeight: '900',
    lineHeight: 18,
  },
  emptyHomeText: {
    color: '#F8F4FF',
    fontSize: 15,
    fontWeight: '900',
    letterSpacing: 0.4,
  },
  emptyTitle: {
    fontSize: 25,
    fontWeight: '800',
    color: colors.textDark,
    textAlign: 'center',
  },
  emptyText: {
    marginTop: 10,
    textAlign: 'center',
    color: colors.textMuted,
    fontSize: 15,
    lineHeight: 22,
  },
  quizCard: {
    marginTop: 14,
    backgroundColor: 'rgba(8,11,22,0.82)',
    borderRadius: 32,
    padding: 12,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 14 },
    shadowOpacity: 0.34,
    shadowRadius: 24,
    elevation: 10,
  },
  questionPanel: {
    minHeight: 100,
    borderRadius: 26,
    paddingHorizontal: 18,
    paddingTop: 18,
    paddingBottom: 20,
    justifyContent: 'center',
    backgroundColor: 'rgba(18,10,34,0.92)',
  },
  questionMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  panelTitle: {
    color: 'rgba(244,247,255,0.72)',
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
    flex: 1,
    marginRight: 10,
  },
  questionCounterText: {
    fontSize: 14,
    fontWeight: '800',
    color: 'rgba(255,255,255,0.92)',
    textAlign: 'right',
  },
  questionTitle: {
    color: '#F6F8FF',
    textAlign: 'center',
    fontSize: 18,
    lineHeight: 25,
    fontWeight: '700',
  },
  timeRow: {
    marginTop: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  timeClockWrap: {
    width: 44,
    height: 44,
    marginRight: 8,
    flexShrink: 0,
    alignItems: 'center',
    justifyContent: 'center',
  },
  timeBar: {
    flex: 1,
    height: 8,
    borderRadius: 999,
    backgroundColor: 'rgba(255,255,255,0.08)',
    overflow: 'hidden',
  },
  timeFill: {
    height: '100%',
    borderRadius: 999,
  },
  timeValue: {
    marginLeft: 8,
    color: '#F4F7FF',
    fontSize: 13,
    fontWeight: '700',
    minWidth: 52,
    textAlign: 'right',
    lineHeight: 16,
    includeFontPadding: false,
    textAlignVertical: 'center',
  },
  optionsGroup: {
    marginTop: 16,
  },
  feedbackSection: {
    marginTop: 16,
  },
  feedbackCard: {
    marginBottom: 14,
    backgroundColor: 'rgba(8,11,22,0.82)',
    borderRadius: 20,
    padding: 14,
    borderWidth: 1,
    borderColor: 'rgba(139,92,246,0.18)',
  },
  feedbackRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  crossCircle: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: '#FF7F63',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 8,
  },
  crossText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '700',
  },
  feedback: {
    flex: 1,
    fontSize: 15,
    lineHeight: 22,
    fontWeight: '600',
  },
  correct: {
    color: colors.success,
  },
  incorrect: {
    color: '#E06E43',
  },
  answerText: {
    marginTop: 8,
    color: colors.textMuted,
    fontSize: 14,
    lineHeight: 20,
  },
  feedbackPlaceholder: {
    marginBottom: 14,
    backgroundColor: 'rgba(7,10,18,0.66)',
    borderRadius: 18,
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderWidth: 1,
    borderColor: 'rgba(84,150,255,0.16)',
  },
  feedbackPlaceholderText: {
    color: colors.textMuted,
    fontSize: 13,
  },
});
