import { StyleSheet } from 'react-native';
import { colors } from '../../style/colors';
import { fontScale, radiusScale, spaceScale } from '../../style/responsive';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: colors.background,
  },
  container: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: spaceScale(18),
    paddingTop: spaceScale(14),
    paddingBottom: spaceScale(116),
  },
  topUtilityRow: {
    marginBottom: spaceScale(10),
  },
  topUtilityCopy: {
    flex: 1,
  },
  topUtilityEyebrow: {
    color: 'rgba(125,211,252,0.88)',
    fontSize: fontScale(12),
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 0.9,
  },
  topUtilityTitle: {
    marginTop: spaceScale(5),
    color: '#F8FBFF',
    fontSize: fontScale(18),
    fontWeight: '900',
  },
  topUtilitySubtext: {
    marginTop: spaceScale(5),
    color: 'rgba(214,235,242,0.72)',
    fontSize: fontScale(10),
    lineHeight: fontScale(18),
    fontWeight: '600',
  },
  spotlightCircleRow: {
    paddingTop: spaceScale(4),
    paddingBottom: spaceScale(10),
    paddingRight: spaceScale(12),
    gap: spaceScale(12),
  },
  spotlightTouch: {
    alignItems: 'center',
    justifyContent: 'center',
    width: spaceScale(78),
  },
  spotlightTouchFeatured: {
    width: spaceScale(92),
  },
  spotlightRingShell: {
    width: spaceScale(72),
    height: spaceScale(72),
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  spotlightRingShellFeatured: {
    width: spaceScale(82),
    height: spaceScale(82),
  },
  spotlightRing: {
    ...StyleSheet.absoluteFillObject,
    borderRadius: radiusScale(999),
    padding: spaceScale(3),
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#FB923C',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.2,
    shadowRadius: 14,
    elevation: 5,
  },
  spotlightRingFeatured: {
    shadowColor: '#F59E0B',
    shadowOffset: { width: 0, height: 16 },
    shadowOpacity: 0.38,
    shadowRadius: 22,
    elevation: 10,
  },
  spotlightWinnerHalo: {
    position: 'absolute',
    width: '112%',
    height: '112%',
    borderRadius: radiusScale(999),
    backgroundColor: 'rgba(245, 158, 11, 0.16)',
  },
  spotlightInnerRing: {
    width: '91.5%',
    height: '91.5%',
    borderRadius: radiusScale(999),
    backgroundColor: 'rgba(5,19,28,0.95)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.12)',
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  spotlightInnerRingFeatured: {
    borderColor: 'rgba(255, 221, 120, 0.72)',
    borderWidth: 1.5,
    backgroundColor: 'rgba(56, 33, 7, 0.98)',
  },
  spotlightInitialsFeatured: {
    color: '#FFF3C4',
    fontSize: fontScale(20),
    textShadowColor: 'rgba(245, 158, 11, 0.35)',
    textShadowRadius: 8,
  },
  spotlightInitials: {
    color: '#F8FBFF',
    fontSize: fontScale(18),
    fontWeight: '900',
    letterSpacing: 0.4,
  },
  spotlightLikeBadge: {
    position: 'absolute',
    bottom: spaceScale(5),
    right: spaceScale(5),
    minWidth: spaceScale(24),
    height: spaceScale(20),
    paddingHorizontal: spaceScale(5),
    borderRadius: radiusScale(999),
    backgroundColor: 'rgba(15,23,42,0.96)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.12)',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spaceScale(3),
  },
  spotlightLikeBadgeFeatured: {
    backgroundColor: 'rgba(90, 49, 6, 0.96)',
    borderColor: 'rgba(255, 221, 120, 0.34)',
  },
  spotlightLikeBadgeText: {
    color: '#FFF7FB',
    fontSize: fontScale(8),
    fontWeight: '900',
  },
  spotlightLabel: {
    marginTop: spaceScale(6),
    color: 'rgba(248,251,255,0.82)',
    fontSize: fontScale(10),
    fontWeight: '800',
    textAlign: 'center',
  },
  spotlightLabelFeatured: {
    color: '#FDE68A',
    fontSize: fontScale(11),
    fontWeight: '900',
  },
  spotlightLoadingCircle: {
    width: spaceScale(72),
    height: spaceScale(72),
    borderRadius: radiusScale(999),
    backgroundColor: 'rgba(5,19,28,0.92)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  spotlightEmptyState: {
    minWidth: spaceScale(220),
    paddingHorizontal: spaceScale(16),
    paddingVertical: spaceScale(14),
    borderRadius: radiusScale(20),
    backgroundColor: 'rgba(255,255,255,0.08)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.12)',
  },
  spotlightEmptyTitle: {
    color: '#F8FBFF',
    fontSize: fontScale(14),
    fontWeight: '900',
  },
  spotlightEmptyText: {
    marginTop: spaceScale(6),
    color: 'rgba(214,235,242,0.72)',
    fontSize: fontScale(11),
    lineHeight: fontScale(17),
    fontWeight: '600',
  },
  glowTop: {
    position: 'absolute',
    top: -100,
    right: -60,
    width: 250,
    height: 250,
    borderRadius: 250,
    backgroundColor: 'rgba(20,184,166,0.18)',
  },
  glowBottom: {
    position: 'absolute',
    bottom: 120,
    left: -80,
    width: 220,
    height: 220,
    borderRadius: 220,
    backgroundColor: 'rgba(56,189,248,0.12)',
  },
  glowAccent: {
    position: 'absolute',
    top: 240,
    right: -50,
    width: 180,
    height: 180,
    borderRadius: 180,
    backgroundColor: 'rgba(251,146,60,0.12)',
  },
  heroCard: {
    padding: spaceScale(16),
    borderRadius: radiusScale(30),
    backgroundColor: 'rgba(255,255,255,0.08)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.12)',
    overflow: 'hidden',
  },
  heroBanner: {
    marginTop: spaceScale(8),
    position: 'relative',
    borderRadius: radiusScale(24),
    overflow: 'hidden',
    backgroundColor: 'rgba(255,255,255,0.06)',
  },
  heroStudentImage: {
    width: '100%',
    height: spaceScale(126),
  },
  greeting: {
    color: '#F8FBFF',
    fontSize: fontScale(16),
    lineHeight: fontScale(20),
    fontWeight: '900',
  },
  heroStrip: {
    marginTop: spaceScale(18),
    flexDirection: 'row',
    gap: spaceScale(10),
  },
  heroStatCard: {
    flex: 1,
    borderRadius: radiusScale(20),
    paddingVertical: spaceScale(14),
    paddingHorizontal: spaceScale(10),
    backgroundColor: 'rgba(6,23,34,0.42)',
    alignItems: 'center',
  },
  heroStatValue: {
    color: '#F8FBFF',
    fontSize: fontScale(18),
    fontWeight: '900',
  },
  heroStatLabel: {
    marginTop: spaceScale(4),
    color: 'rgba(214,235,242,0.72)',
    fontSize: fontScale(10),
    fontWeight: '700',
    textAlign: 'center',
  },
  continueCard: {
    marginTop: spaceScale(18),
    borderRadius: radiusScale(24),
    padding: spaceScale(16),
    flexDirection: 'row',
    alignItems: 'center',
    gap: spaceScale(12),
  },
  continueCopy: {
    flex: 1,
  },
  continueKicker: {
    color: 'rgba(248,251,255,0.74)',
    fontSize: fontScale(11),
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  continueTitle: {
    marginTop: spaceScale(8),
    color: '#F8FBFF',
    fontSize: fontScale(20),
    fontWeight: '900',
  },
  continueMeta: {
    marginTop: spaceScale(4),
    color: 'rgba(248,251,255,0.74)',
    fontSize: fontScale(12),
    fontWeight: '600',
  },
  continueButtonWrap: {
    overflow: 'hidden',
    borderRadius: radiusScale(999),
  },
  continueButton: {
    minHeight: spaceScale(44),
    paddingHorizontal: spaceScale(18),
    borderRadius: radiusScale(999),
    alignItems: 'center',
    justifyContent: 'center',
  },
  continueButtonText: {
    color: '#F8FBFF',
    fontSize: fontScale(12),
    fontWeight: '900',
  },
  sectionHeader: {
    marginTop: spaceScale(22),
  },
  sectionTitle: {
    color: '#F8FBFF',
    fontSize: fontScale(20),
    fontWeight: '900',
  },
  sectionText: {
    marginTop: spaceScale(5),
    color: 'rgba(214,235,242,0.72)',
    fontSize: fontScale(12),
    lineHeight: fontScale(18),
  },
  quickActionRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginTop: spaceScale(14),
  },
  quickTouch: {},
  quickCard: {
    borderRadius: radiusScale(28),
    overflow: 'hidden',
    justifyContent: 'space-between',
    shadowColor: '#04111A',
    shadowOffset: { width: 0, height: 14 },
    shadowOpacity: 0.22,
    shadowRadius: 20,
    elevation: 6,
  },
  quickCardImage: {
    borderRadius: radiusScale(28),
  },
  quickCardOverlay: {
    ...StyleSheet.absoluteFillObject,
  },
  quickGlow: {
    position: 'absolute',
    right: -18,
    top: -20,
    width: spaceScale(92),
    height: spaceScale(92),
    borderRadius: radiusScale(999),
  },
  quickOrbOne: {
    position: 'absolute',
    left: -18,
    bottom: -26,
    width: spaceScale(66),
    height: spaceScale(66),
    borderRadius: radiusScale(999),
    backgroundColor: 'rgba(255,255,255,0.08)',
  },
  quickOrbTwo: {
    position: 'absolute',
    right: 16,
    top: 46,
    width: spaceScale(34),
    height: spaceScale(34),
    borderRadius: radiusScale(999),
    backgroundColor: 'rgba(255,255,255,0.08)',
  },
  quickCardTop: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spaceScale(10),
  },
  quickEyebrow: {
    color: 'rgba(248,251,255,0.92)',
    fontSize: fontScale(10),
    fontWeight: '800',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
    textShadowColor: 'rgba(3,16,24,0.8)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 6,
  },
  quickIconShell: {
    borderRadius: radiusScale(14),
    backgroundColor: 'rgba(5,18,27,0.34)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.18)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  quickCopy: {
    marginTop: spaceScale(10),
    marginBottom: spaceScale(10),
    alignSelf: 'flex-start',
    maxWidth: '88%',
    paddingHorizontal: spaceScale(8),
    paddingVertical: spaceScale(8),
    borderRadius: radiusScale(16),
    backgroundColor: 'rgba(5,18,27,0.34)',
  },
  quickCopyLight: {
    backgroundColor: 'rgba(5,18,27,0.22)',
  },
  quickCopyPinned: {
    position: 'absolute',
    alignSelf: 'flex-start',
    left: spaceScale(10),
    bottom: spaceScale(5),
    marginTop: 0,
    marginBottom: 0,
  },
  quickTitle: {
    color: '#F8FBFF',
    fontWeight: '900',
    textAlign: 'left',
    textShadowColor: 'rgba(3,16,24,0.82)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 8,
  },
  quickMeta: {
    marginTop: spaceScale(3),
    color: 'rgba(248,251,255,0.96)',
    textAlign: 'left',
    textShadowColor: 'rgba(3,16,24,0.82)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 8,
  },
  topicHeader: {
    marginTop: spaceScale(22),
    marginBottom: spaceScale(12),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  linkText: {
    color: colors.accentGold,
    fontSize: fontScale(12),
    fontWeight: '800',
  },
  topicRow: {
    flexDirection: 'row',
    gap: spaceScale(10),
    paddingRight: spaceScale(18),
  },
  topicTouch: {
    flexShrink: 0,
  },
  topicCard: {
    minHeight: spaceScale(96),
    borderRadius: radiusScale(24),
    paddingHorizontal: spaceScale(13),
    paddingVertical: spaceScale(12),
    alignItems: 'flex-start',
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.12)',
    shadowColor: '#031018',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.18,
    shadowRadius: 18,
    elevation: 5,
  },
  topicCardImage: {
    borderRadius: radiusScale(24),
  },
  topicCardOverlay: {
    ...StyleSheet.absoluteFillObject,
  },
  topicTopRow: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    gap: spaceScale(8),
    paddingHorizontal: spaceScale(8),
    paddingVertical: spaceScale(6),
    borderRadius: radiusScale(999),
    backgroundColor: 'rgba(4,16,24,0.28)',
  },
  topicGlow: {
    position: 'absolute',
    bottom: -18,
    right: -10,
    width: spaceScale(68),
    height: spaceScale(68),
    borderRadius: radiusScale(999),
  },
  topicShine: {
    position: 'absolute',
    top: -18,
    right: -10,
    width: spaceScale(72),
    height: spaceScale(72),
    borderRadius: radiusScale(999),
    backgroundColor: 'rgba(255,255,255,0.10)',
  },
  topicIconWrap: {
    width: spaceScale(32),
    height: spaceScale(32),
    borderRadius: radiusScale(11),
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.16)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  topicKicker: {
    flex: 1,
    color: 'rgba(248,251,255,0.94)',
    fontSize: fontScale(8),
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    textShadowColor: 'rgba(3,16,24,0.78)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 6,
  },
  topicBottomRow: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spaceScale(8),
    marginTop: spaceScale(12),
    paddingHorizontal: spaceScale(8),
    paddingVertical: spaceScale(7),
    borderRadius: radiusScale(16),
    backgroundColor: 'rgba(4,16,24,0.34)',
  },
  topicLabel: {
    color: '#F8FBFF',
    fontSize: fontScale(12),
    fontWeight: '900',
    textAlign: 'left',
    flex: 1,
    textShadowColor: 'rgba(3,16,24,0.82)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 8,
  },
  topicMeta: {
    color: 'rgba(248,251,255,0.94)',
    fontSize: fontScale(9),
    fontWeight: '700',
    textAlign: 'right',
    textShadowColor: 'rgba(3,16,24,0.82)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 8,
  },
  storyTouch: {
    marginTop: spaceScale(16),
  },
  storyCard: {
    borderRadius: radiusScale(24),
    padding: spaceScale(16),
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.12)',
  },
  storyCardImage: {
    borderRadius: radiusScale(24),
  },
  storyCardOverlay: {
    ...StyleSheet.absoluteFillObject,
  },
  storyGlowPrimary: {
    position: 'absolute',
    top: -spaceScale(26),
    right: -spaceScale(22),
    width: spaceScale(118),
    height: spaceScale(118),
    borderRadius: radiusScale(999),
    backgroundColor: 'rgba(125,211,252,0.22)',
  },
  storyGlowSecondary: {
    position: 'absolute',
    bottom: -spaceScale(34),
    left: -spaceScale(14),
    width: spaceScale(108),
    height: spaceScale(108),
    borderRadius: radiusScale(999),
    backgroundColor: 'rgba(251,191,36,0.18)',
  },
  storySparkleOne: {
    position: 'absolute',
    top: spaceScale(18),
    right: spaceScale(112),
    width: spaceScale(10),
    height: spaceScale(10),
    borderRadius: radiusScale(999),
    backgroundColor: 'rgba(255,255,255,0.58)',
  },
  storySparkleTwo: {
    position: 'absolute',
    bottom: spaceScale(26),
    right: spaceScale(132),
    width: spaceScale(8),
    height: spaceScale(8),
    borderRadius: radiusScale(999),
    backgroundColor: 'rgba(253,230,138,0.82)',
  },
  storyContentColumn: {
    gap: spaceScale(12),
  },
  storyTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spaceScale(8),
    alignSelf: 'flex-start',
    paddingHorizontal: spaceScale(10),
    paddingVertical: spaceScale(8),
    borderRadius: radiusScale(999),
    backgroundColor: 'rgba(7,23,34,0.34)',
  },
  storyTitleText: {
    color: '#FFF7C2',
    fontSize: fontScale(18),
    fontWeight: '900',
    textShadowColor: 'rgba(4,12,18,0.86)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 8,
  },
  storyCopyWrap: {
    alignSelf: 'flex-start',
    paddingHorizontal: spaceScale(12),
    paddingVertical: spaceScale(12),
    borderRadius: radiusScale(18),
    backgroundColor: 'rgba(7,23,34,0.3)',
  },
  storyTagRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spaceScale(8),
  },
  storyTag: {
    minHeight: spaceScale(30),
    paddingHorizontal: spaceScale(12),
    borderRadius: radiusScale(999),
    alignItems: 'center',
    justifyContent: 'center',
  },
  storyTagBlue: {
    backgroundColor: 'rgba(56,189,248,0.32)',
  },
  storyTagGold: {
    backgroundColor: 'rgba(251,191,36,0.34)',
  },
  storyTagMint: {
    backgroundColor: 'rgba(45,212,191,0.34)',
  },
  storyTagText: {
    color: '#F8FBFF',
    fontSize: fontScale(11),
    fontWeight: '800',
    textShadowColor: 'rgba(4,12,18,0.72)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 6,
  },
  storyCtaWrap: {
    alignSelf: 'flex-start',
    marginTop: spaceScale(14),
    minHeight: spaceScale(34),
    paddingHorizontal: spaceScale(14),
    borderRadius: radiusScale(999),
    backgroundColor: 'rgba(255,255,255,0.22)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.2)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  storyCtaText: {
    color: '#FFFFFF',
    fontSize: fontScale(11),
    fontWeight: '900',
    letterSpacing: 0.4,
    textTransform: 'uppercase',
    textShadowColor: 'rgba(4,12,18,0.76)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 6,
  },
  storyArtShell: {
    width: '100%',
    height: spaceScale(112),
    borderRadius: radiusScale(20),
    overflow: 'hidden',
    backgroundColor: 'rgba(255,255,255,0.09)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.12)',
  },
  storyArt: {
    width: '100%',
    height: '100%',
  },
  snapshotCard: {
    marginTop: spaceScale(18),
    padding: spaceScale(16),
    borderRadius: radiusScale(26),
    backgroundColor: 'rgba(255,255,255,0.08)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.12)',
  },
  snapshotTitle: {
    color: '#F8FBFF',
    fontSize: fontScale(18),
    fontWeight: '900',
  },
  snapshotGrid: {
    marginTop: spaceScale(14),
    flexDirection: 'row',
    gap: spaceScale(10),
  },
  snapshotItem: {
    flex: 1,
    borderRadius: radiusScale(18),
    paddingVertical: spaceScale(14),
    paddingHorizontal: spaceScale(10),
    backgroundColor: 'rgba(6,23,34,0.4)',
  },
  snapshotValue: {
    color: '#F8FBFF',
    fontSize: fontScale(18),
    fontWeight: '900',
  },
  snapshotLabel: {
    marginTop: spaceScale(5),
    color: 'rgba(214,235,242,0.72)',
    fontSize: fontScale(10),
    fontWeight: '700',
  },
  progressList: {
    marginTop: spaceScale(12),
  },
  progressRow: {
    marginTop: spaceScale(12),
  },
  progressRowTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: spaceScale(12),
  },
  progressName: {
    color: '#F8FBFF',
    fontSize: fontScale(13),
    fontWeight: '700',
    flex: 1,
  },
  progressPercent: {
    color: 'rgba(214,235,242,0.72)',
    fontSize: fontScale(12),
    fontWeight: '700',
  },
  progressTrack: {
    marginTop: spaceScale(7),
    height: spaceScale(6),
    borderRadius: radiusScale(999),
    backgroundColor: 'rgba(255,255,255,0.08)',
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    borderRadius: radiusScale(999),
  },
  spotlightModalRoot: {
    flex: 1,
  },
  spotlightModalBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(2,10,15,0.76)',
  },
  spotlightModalCard: {
    flex: 1,
    overflow: 'hidden',
  },
  spotlightModalGradient: {
    flex: 1,
    paddingHorizontal: spaceScale(18),
    paddingTop: spaceScale(12),
    paddingBottom: spaceScale(22),
    overflow: 'hidden',
  },
  spotlightModalGlowOne: {
    position: 'absolute',
    top: -spaceScale(40),
    right: -spaceScale(28),
    width: spaceScale(140),
    height: spaceScale(140),
    borderRadius: radiusScale(999),
    backgroundColor: 'rgba(56,189,248,0.16)',
  },
  spotlightModalGlowTwo: {
    position: 'absolute',
    bottom: -spaceScale(48),
    left: -spaceScale(24),
    width: spaceScale(132),
    height: spaceScale(132),
    borderRadius: radiusScale(999),
    backgroundColor: 'rgba(251,146,60,0.14)',
  },
  spotlightModalHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: spaceScale(12),
  },
  spotlightModalHeaderCopy: {
    flex: 1,
  },
  spotlightModalEyebrow: {
    color: 'rgba(125,211,252,0.86)',
    fontSize: fontScale(11),
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 0.9,
  },
  spotlightModalTitle: {
    marginTop: spaceScale(6),
    color: '#F8FBFF',
    fontSize: fontScale(24),
    fontWeight: '900',
  },
  spotlightModalClose: {
    width: spaceScale(38),
    height: spaceScale(38),
    borderRadius: radiusScale(999),
    backgroundColor: 'rgba(255,255,255,0.1)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.14)',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#F59E0B',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.18,
    shadowRadius: 10,
    elevation: 4,
  },
  colorfulCloseGlyph: {
    width: spaceScale(18),
    height: spaceScale(18),
    alignItems: 'center',
    justifyContent: 'center',
  },
  colorfulCloseStroke: {
    position: 'absolute',
    width: '100%',
    height: spaceScale(3),
    borderRadius: radiusScale(999),
  },
  colorfulCloseStrokeForward: {
    transform: [{ rotate: '45deg' }],
  },
  colorfulCloseStrokeBackward: {
    transform: [{ rotate: '-45deg' }],
  },
  spotlightPostAuthorRow: {
    marginTop: spaceScale(18),
    flexDirection: 'row',
    alignItems: 'center',
    gap: spaceScale(12),
  },
  spotlightPostAvatar: {
    width: spaceScale(52),
    height: spaceScale(52),
    borderRadius: radiusScale(999),
    alignItems: 'center',
    justifyContent: 'center',
  },
  spotlightPostAvatarText: {
    color: '#031018',
    fontSize: fontScale(18),
    fontWeight: '900',
  },
  spotlightPostMeta: {
    flex: 1,
  },
  spotlightPostAuthorName: {
    color: '#F8FBFF',
    fontSize: fontScale(16),
    fontWeight: '900',
  },
  spotlightPostDate: {
    marginTop: spaceScale(4),
    color: 'rgba(214,235,242,0.68)',
    fontSize: fontScale(11),
    fontWeight: '700',
  },
  spotlightPostLikePill: {
    minHeight: spaceScale(34),
    paddingHorizontal: spaceScale(12),
    borderRadius: radiusScale(999),
    backgroundColor: 'rgba(251,146,60,0.18)',
    borderWidth: 1,
    borderColor: 'rgba(251,191,36,0.24)',
    flexDirection: 'row',
    alignItems: 'center',
    gap: spaceScale(6),
  },
  spotlightPostLikeText: {
    color: '#FFF7FB',
    fontSize: fontScale(12),
    fontWeight: '900',
  },
  spotlightPostTitle: {
    marginTop: spaceScale(18),
    color: '#F8FBFF',
    fontSize: fontScale(21),
    lineHeight: fontScale(27),
    fontWeight: '900',
  },
  spotlightPostBodyScroll: {
    marginTop: spaceScale(12),
    flex: 1,
  },
  spotlightPostBodyScrollContent: {
    paddingBottom: spaceScale(18),
  },
  spotlightPostBody: {
    color: 'rgba(236,247,252,0.88)',
    fontSize: fontScale(14),
    lineHeight: fontScale(22),
    fontWeight: '600',
  },
  spotlightOpenFeedTouch: {
    marginTop: spaceScale(18),
    borderRadius: radiusScale(999),
    overflow: 'hidden',
  },
  spotlightOpenFeedButton: {
    minHeight: spaceScale(48),
    borderRadius: radiusScale(999),
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: spaceScale(18),
  },
  spotlightOpenFeedText: {
    color: '#F8FBFF',
    fontSize: fontScale(12),
    fontWeight: '900',
    letterSpacing: 0.5,
    textTransform: 'uppercase',
  },
});
